### ISSUE TITLE
istio config kinds share the same k8s TPR kind

### ISSUE THREAD

**Issue by esnible** [istio/manager#203]
`./manager/bazel-bin/cmd/manager/manager config list --help` produces output including ```Usage:
  manager config list [kind...] [flags]```

The word "kind" here is confusing.  According to manager, "route-rule" is a "kind".  According to `kubectl get istioconfig` the kind is "IstioConfig.v1alpha1.istio.io".  I found that confusing.  The usage should include the valid values.

I also found it confusing that `kubectl get istioconfig` believes my resource is named "route-rule-reviews-v1" but the name that was needed by `manager config delete route-rule ...` did not have the route-rule- prefix.

**Comment by kyessenov** [comment]
We do not map Istio config kind to Kubernetes kind 1-to-1, simply because there's a lot of overhead with adding new TPR kinds. Each TPR requires 5 new structs with interface definitions. Once we have a solution to the overhead (with codegen or maybe k8s will fix this), we can map each istio kind to k8s kind exactly.

So right now, route-rule my-rule maps to k8s istioconfig with name route-rule-my-rule.

**Comment by rshriram** [comment]
Why is this even a bug in the first place? Its more of a TODO. Secondly, if we are taking the istioctl route, I don't think we should bother telling the user how we store and retrieve configs from Kubernetes. Otherwise, it will lead to all sorts of confusions (like people trying to add TPRs and retrieve it via istioctl, etc.). I suggest we maintain one single external interface (istioctl) that is platform agnostic. It gives us the ability to change the underlying storage mechanism as kubernetes evolves (we may be using TPRs today, but tomorrow we might end up using something else completely if kubernetes comes up with a different concept -- thereby breaking our tool chains, and stuff).

**Comment by rshriram** [comment]
closing this as istioctl or REST API layer ( #227 ) will solve the same problem
