### ISSUE TITLE
New istioctl create implementation incompatible with update and delete

### ISSUE THREAD

**Issue by frankbu** [istio/manager#286]
Now that `create` includes the type and name in the input file, instead of as args, `update` must do the same, otherwise you can't just modify a rule file and then use it for update ... you need a totally different file. `delete` should also allow `-f` as only arg. Also, maybe `update` should be renamed to `replace` to be consistent with kubectl.

**Comment by esnible** [comment]
On Slack, @frankbu said "2) For usability reasons, `istioctl update` must work exactly the same as `create`, i.e., only takes the `-f` arg (no name and type). Because `kubectl` has deprecated `update`, changed it to `replace`, I think `istioctl` should do the same. 3) `istioctl delete` can stay as is for now, but I think it would be nice to also support `istioctl delete -f file.yaml`, since that's a very convenient pattern that `kubectl` supports for it's resources"

**Comment by esnible** [comment]
Delivered fix for `istioctl replace`.  Changes for `istioctl delete` can wait for a separate
