### ISSUE TITLE
need validation for proxymeshconfig

### ISSUE THREAD

**Issue by rshriram** [istio/manager#539]
We currently have validation for the routing proto, but lack validation for the ProxyMeshConfig which also touches some aspects of Envoy config. For example, users can set the cluster connect timeout via the proxy mesh config. These fields need to be validated/sanitized to ensure that incorrect values ( negative timeouts) don't creep in (this would cause Envoy to crash).

**Comment by esnible** [comment]
Can you explain where the ProxyMeshConfig is documented?  I found _istio/api/proxy/v1/config/cfg.proto_:57-8 which just reads

```
message ProxyMeshConfig {
}
```

Yet if I do `kubectl get cm istio --output yaml` I see mixerAddress and discoveryAddress in there!

If there is something more concrete would be happy to write validation for this.  I am unsure where the validation should go.  We don't use istioctl to manipulate the ProxyMeshConfig do we?  We use kubectl.

We have Issue #325 which seems to be about this.  Kubernetes has a Feature Request https://github.com/kubernetes/kubernetes/issues/38117 about this

Would it be sufficient to write a command line that validates the contents of the Istio and/or mixer-config and returns a 0 or non-zero?

**Comment by kyessenov** [comment]
Hi, you probably have on older revision of istio/api repo. The location is correct: https://github.com/istio/api/blob/master/proxy/v1/config/cfg.proto#L60

I think I should tackle this task since I was the one who introduced this proto in the first place. I'll send our a PR soon-ish. I think it's more important to validate on start-up for the first PR so we get consistent failures rather than hard-to-debug proxy errors during operation. The issue you referenced is a long-standing blocker in k8s that seems to be planned for k8s >=1.8.
