### ISSUE TITLE
Virtual host with port redirect

### ISSUE THREAD

**Issue by kyessenov** [istio/manager#56]
According to [rfc2616](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.23), host header may have the port value as a suffix. It seems that with the recent port redirection, Envoy "domain" "a" does not accept requests with a header "a:80" .

**Comment by enricoschiattarella** [comment]
I am not sure what is the issue here and why port redirect matters.

My understanding is that the host header is intended to be consumed by the final destination server.
It is ok for the proxy to make decisions based on that, and we may add the logic to the proxy if we need it and it is not there.

Consider, however, the case in which the client tries to open a connection to a webserver on port 80 and specifies service1:80 in the host header. The proxy will see the incoming connection on port 80. I think the correct behavior for the proxy would still be to try to connect to the final webserver on port 80 and pass the host header unchanged. Basically the behavior, as observed by the receiving webserver, is unchanged (source IP address might be different in the per-node case).

The discussion above ignores port redirect. If you add port-redirect to the mix, now what might happen is that the proxy is actually listening on port 12345 and the connection destined to port 80 gets picked up by the listener listening on port 12345. However, the listener on port 12345 understands that the connection should be handled by the listener for port 80 (which may or may not listen) and hands it off. From this point on, everything proceeds as described in the paragraph above.

What is wrong/missing ?

**Comment by kyessenov** [comment]
It seems there might be a bug in that Envoy _does not_ route virtual host "host:80" the same way as "host" with iptables port redirection. I'll investigate.

**Comment by kyessenov** [comment]
So it sounds like Envoy is just taking literal host value with no processing...
