### ISSUE TITLE
Implement Ingress Controller for Envoy

### ISSUE THREAD

**Issue by louiscryan** [istio/manager#6]
As a proof of concept of the abstraction model we should implement standard Ingress support for Envoy. Should not need any additional configuration artifacts beyond what K8S supports today.

**Comment by kyessenov** [comment]
That sounds like a good target. I would add that Manager needs to support a regular proxy config, in addition to Istio Proxy, to fully reproduce an ingress controller. There is a difference in proxy topology for the edge proxy.

**Comment by elevran** [comment]
@louiscryan @kyessenov trying to flesh out the scope, please weigh in so we're on the same page.

This is my understanding of the task, as worded:
Run the manager as an ingress controller to setup Envoy as a standard Ingress controller, only basic k8s Ingress functionality. Later extend to support full Istio functionality.

Since this issue was first written, things have evolved. Is the above still a correct rephrasing of what's needed?

**Comment by louiscryan** [comment]
Yes, that's correct.

**Comment by elevran** [comment]
Merged in #71 #177

**Comment by zcahana** [comment]
Opened a bunch of follow-up issues, so that we can track and prioritize future work on the ingress controller:

- #214: Ingress controller: update ingress resource status
- #215: Ingress controller: support ingress class annotation
- #216: Ingress controller: TLS support
- #217: Ingress controller: support Istio routing rules
- #218: Ingress controller: integrate with Istio mixer
- #219: Ingress controller: evaluate kubernetes GenericController as a base implementation
- #220: Ingress controller: start proxy process regardless of existing ingress resources

**Comment by zcahana** [comment]
Also note #151 which tracks some additional issues relating to ingress rules vs. Istio's rules.
